#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to another URL with a 301 status

# Backup the existing Nginx config
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add the redirection rule
sudo sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

