#!/usr/bin/env bash
# This script configures Nginx to serve a custom 404 page

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Update Nginx config to use the custom 404 page
sudo sed -i '/server_name _;/a \\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

